on:
    push:
    pull_request:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'
            - run: npm ci
            - run: npm run ci-build
            - run: npm run build
            - name: Publish
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ants
                  directory: dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
